web:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./apps:/var/www/html
        - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
php:
    image: php:7-fpm
    volumes:
        - ./apps:/var/www/html
composer:
    restart: 'no'
    image: composer:latest
    command: install
    volumes:
        - ./apps/gastrologi:/app
